apiVersion: v1
kind: Secret
metadata:
  name: env-checker-ui-access-token
  labels:
    app.kubernetes.io/name: '{{ .Values.SERVICE_NAME }}'
    app.kubernetes.io/part-of: '{{ .Values.APPLICATION_NAME }}'
    app.kubernetes.io/managed-by: '{{ .Values.MANAGED_BY }}'
type: Opaque
stringData:
  {{- if .Values.ENVIRONMENT_CHECKER_UI_ACCESS_TOKEN }}
  access-token: {{ .Values.ENVIRONMENT_CHECKER_UI_ACCESS_TOKEN }}
  {{- else }}
  access-token: f9a3bd4e9f2c3be01cd629154cfb224c2703181e050254b5
  {{- end }}